FROM apache/airflow:latest

RUN pip install --no-cache-dir --user dbt-postgres

RUN pip install --no-cache-dir --user airflow-dbt

RUN pip install --no-cache-dir --user dbt-redshift

RUN pip install --no-cache-dir --user dbt-snowflake

RUN pip install --no-cache-dir --user dbt-bigquery